# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 462d86694cb8669dd8e0aff921f256ec0b7104bb3f0d60a6ba338fe4039bad324f3b0b6e0133e0e7a61151b91d4fb9bb19f794892a96cd23c5aaa058b252d837

test:
  secret_key_base: f9bcf4a69e71f3f69dbfe3ae8c643584c3db212bd97272402054a7153ca577f3599e1928f8e09a98267b45f6581ae91f1353db62f4267ee7ad1f74999124551d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
